services:
  demo:
    build:
      context: .
    ports:
      - "9011:9011"
    restart: always
    network_mode: "host"
    volumes:
      - /data/projects/moliy/docs/predictions:/app/database
      - /data/projects/moliy/docs/uploads:/app/uploads